In [1]:
# Create a NumPy array:
# [1.0, 2.5, np.nan, 4.1, np.nan, 6.0]
import numpy as np
arr = np.array([1.0, 2.5, np.nan, 4.1, np.nan, 6.0])
print(arr)

[1.  2.5 nan 4.1 nan 6. ]


In [2]:
# Check and print which values in the array are NaN.
import numpy as np
arr = np.array([1.0, 2.5, np.nan, 4.1, np.nan, 6.0])
print(arr)

[1.  2.5 nan 4.1 nan 6. ]


In [3]:
# Count the total number of NaN values in the array.
# [1.0, 2.5, np.nan, 4.1, np.nan, 6.0]
arr = np.array([1.0, 2.5, np.nan, 4.1, np.nan, 6.0])
count = np.isnan(arr).sum()
print(count)

2


In [4]:
# Replace all NaN values with 0.
# [1.0, 2.5, np.nan, 4.1, np.nan, 6.0]
import numpy as np
arr = np.array([1.0, 2.5, np.nan, 4.1, np.nan, 6.0])
arr[np.isnan(arr)] = 0
print(arr)

[1.  2.5 0.  4.1 0.  6. ]


In [5]:
# Remove all NaN values and print the cleaned array.
import numpy as np
arr = np.array([1.0, 2.5, np.nan, 4.1, np.nan, 6.0])
cleaned_array = arr[~np.isnan(arr)] 
print(cleaned_array)

[1.  2.5 4.1 6. ]


In [6]:
# Create a 2D array like this:
# [[1, 2, np.nan],
#  # [4, np.nan, 6],
#  [7, 8, 9]]
# Replace all NaN values with -1.
import numpy as np
arr = np.array([[1, 2, np.nan],
                [4, np.nan, 6],
                [7, 8, 9]])
arr[np.isnan(arr)] = -1
print(arr)

[[ 1.  2. -1.]
 [ 4. -1.  6.]
 [ 7.  8.  9.]]


In [7]:
# Count how many NaN values are in each row of the above 2D array
arr = np.array([[1, 2, np.nan],
                [4, np.nan, 6],
                [7, 8, 9]])
count = np.isnan(arr).sum(axis=1)
print(count)

[1 1 0]


In [8]:
# Replace all NaN values with the median of the non-NaN values.
import numpy as np
arr = np.array([1.0, 2.5, np.nan, 4.1, np.nan, 6.0])
median_val = np.nanmedian(arr)
arr[np.isnan(arr)] = median_val
print(arr)

[1.  2.5 3.3 4.1 3.3 6. ]


In [9]:
# Replace all NaN values with the mean of the array (excluding NaN).
import numpy as np
arr = np.array([1.0, 2.5, np.nan, 4.1, np.nan, 6.0])
mean_val = np.nanmean(arr)
arr[np.isnan(arr)] = mean_val
print(arr)

[1.  2.5 3.4 4.1 3.4 6. ]


In [10]:
# Create a NumPy array with values [5, np.nan, 15, 20, np.nan, 30].
# Replace all NaN values with 0.
import numpy as np
arr = np.array([5, np.nan, 15, 20, np.nan, 30])
arr[np.isnan(arr)] = 0
print(arr)

[ 5.  0. 15. 20.  0. 30.]


In [11]:
# Create a NumPy array with 8 float values including 3 NaNs.
# Remove all NaN values and print the cleaned array.
import numpy as np
arr = np.array([5.4, 8.6, 9.4, 8.4, np.nan, np.nan, 15.6, np.nan])
print(arr)
cleaned_array = arr[~np.isnan(arr)]
print(cleaned_array)

[ 5.4  8.6  9.4  8.4  nan  nan 15.6  nan]
[ 5.4  8.6  9.4  8.4 15.6]


In [12]:
# Given an array [2.0, 4.5, np.nan, 6.0, 8.5],
# replace NaN with the mean of non-NaN values.
import numpy as np
arr = np.array([2.0, 4.5, np.nan, 6.0, 8.5])
mean_val = np.nanmean(arr)
arr[np.isnan(arr)] = mean_val
print(arr)

[2.   4.5  5.25 6.   8.5 ]


In [13]:
# Create a 2D array with 2 NaNs.
# Replace all NaN values with -99.
import numpy as np
arr = np.array([[1, 2, np.nan],
                [4, np.nan, 6],
                [7, 8, 9]])
nan_value = np.isnan(arr)
arr[np.isnan(arr)] = -99
print(arr)

[[  1.   2. -99.]
 [  4. -99.   6.]
 [  7.   8.   9.]]


In [14]:
# Count the total number of NaN values in a 1D array.
import numpy as np
arr = np.array([1.0, 2.5, np.nan, 4.1, np.nan, 6.0])
count = np.isnan(arr).sum()
print(count)

2


In [15]:
# Count the number of NaN values in each row of a 3x3 array.
import numpy as np
arr = np.array([[np.nan,2,np.nan],
               [4,5,np.nan],
               [7,8,9]])
count = np.isnan(arr).sum(axis=1)
print(count)

[2 1 0]


In [16]:
# Given a 2D array with NaN values,
# replace each NaN with the mean of its column.
import numpy as np
arr = np.array([[np.nan,2,np.nan],
               [4,5,np.nan],
               [7,8,9]])
nan_with_mean = np.nanmean(arr,axis=0)
arr[np.isnan(arr)] = nan_with_mean
print(arr)

[[5.5 2.  5. ]
 [4.  5.  9. ]
 [7.  8.  9. ]]


In [17]:
# Given a 2D array with NaN values,
# replace each NaN with the mean of its column.
import numpy as np
arr = np.array([[np.nan,2,np.nan],
               [4,5,np.nan],
               [7,8,9]])
mean_val = np.nanmean(arr, axis=0)
for i in range(arr.shape[1]):
    arr[np.isnan(arr[:,i]),i] = mean_val[i]
print(arr)

[[5.5 2.  9. ]
 [4.  5.  9. ]
 [7.  8.  9. ]]


In [18]:
# Given a 3×4 array, replace each NaN with the median of that column.
import numpy as np
arr = np.array([[1,2,np.nan,4],
               [np.nan,np.nan,7,8],
               [9,10,np.nan,12]])
med_value = np.nanmedian(arr,axis=0)
for i in range(arr.shape[1]):
    arr[np.isnan(arr[:,i]),i] = med_value[i]
print(arr)

[[ 1.  2.  7.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10.  7. 12.]]
